from pathlib import Path


def _target_file() -> Path:
    repo_root = Path(__file__).resolve().parent.parent
    return repo_root / "sample_code" / "main.py"


def detect_ai_patterns():
    code = _target_file().read_text(encoding="utf-8")

    if "generated by chatgpt" in code.lower():
        raise Exception("AI-generated code pattern detected")